---
# defaults file for ansible-vsftpd
vsftpd_anonymous_enable: false
vsftpd_connect_from_port_20: true
vsftpd_listen: true
vsftpd_local_enable: true
vsftpd_setype: public_content_t
vsftpd_syslog_enable: true
vsftpd_write_enable: false
vsftpd_chroot_local_user: true
